// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package postgresql

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of Postgres replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each PostgreSQL replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="t1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// TLS configuration for server connections.
	// +kubebuilder:default:={}
	Tls TLS `json:"tls"`
	// PostgreSQL major version to deploy
	// +kubebuilder:default:="v18"
	Version Version `json:"version"`
	// PostgreSQL server configuration.
	// +kubebuilder:default:={}
	Postgresql PostgreSQL `json:"postgresql"`
	// Quorum configuration for synchronous replication.
	// +kubebuilder:default:={}
	Quorum Quorum `json:"quorum"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Databases configuration map.
	// +kubebuilder:default:={}
	Databases map[string]Database `json:"databases,omitempty"`
	// Backup configuration.
	// +kubebuilder:default:={}
	Backup Backup `json:"backup"`
	// Bootstrap configuration.
	// +kubebuilder:default:={}
	Bootstrap Bootstrap `json:"bootstrap"`
}

type Backup struct {
	// Destination path for backups (e.g. s3://bucket/path/).
	// +kubebuilder:default:="s3://bucket/path/to/folder/"
	DestinationPath string `json:"destinationPath,omitempty"`
	// Enable regular backups.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Pre-existing Secret with the CA bundle Barman should trust when reaching a self-signed S3 endpoint. Used for both backup and bootstrap recovery. The CNPG backup driver writes this field on restore.
	// +kubebuilder:default:={}
	EndpointCA EndpointCA `json:"endpointCA,omitempty"`
	// S3 endpoint URL for uploads.
	// +kubebuilder:default:="http://minio-gateway-service:9000"
	EndpointURL string `json:"endpointURL,omitempty"`
	// Retention policy (e.g. "30d").
	// +kubebuilder:default:="30d"
	RetentionPolicy string `json:"retentionPolicy,omitempty"`
	// Access key for S3 authentication. Ignored when `s3CredentialsSecret.name` is set.
	// +kubebuilder:default:="<your-access-key>"
	S3AccessKey string `json:"s3AccessKey,omitempty"`
	// Pre-existing Secret with S3 credentials. When set, the chart references this Secret directly instead of materialising one from `s3AccessKey`/`s3SecretKey`. The CNPG backup driver writes this field on restore so credentials never land in the CR `.spec`.
	// +kubebuilder:default:={}
	S3CredentialsSecret S3CredentialsSecret `json:"s3CredentialsSecret,omitempty"`
	// Secret key for S3 authentication. Ignored when `s3CredentialsSecret.name` is set.
	// +kubebuilder:default:="<your-secret-key>"
	S3SecretKey string `json:"s3SecretKey,omitempty"`
	// Legacy. Cron schedule (CNPG 6-field format) for the chart-emitted ScheduledBackup. Empty means no chart-managed schedule, which is the recommended setup when a `BackupClass` from `backups.cozystack.io` already drives backup orchestration. The chart still emits `spec.backup.barmanObjectStore` whenever `backup.enabled=true`, so `archive_command` runs and the BackupClass driver can take ad-hoc / Plan-driven backups against a live WAL archive.
	// +kubebuilder:default:=""
	Schedule string `json:"schedule,omitempty"`
}

type Bootstrap struct {
	// Whether to restore from a backup.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Previous cluster name before deletion.
	// +kubebuilder:default:=""
	OldName string `json:"oldName"`
	// Timestamp (RFC3339) for point-in-time recovery; empty means latest.
	// +kubebuilder:default:=""
	RecoveryTime string `json:"recoveryTime,omitempty"`
	// Barman server name (S3 path prefix) used by the original cluster when writing backups. Set this only when the original cluster had an explicit barmanObjectStore.serverName that differed from its Kubernetes resource name.
	// +kubebuilder:default:=""
	ServerName string `json:"serverName,omitempty"`
}

type Database struct {
	// List of enabled PostgreSQL extensions.
	Extensions []string `json:"extensions,omitempty"`
	// Roles assigned to users.
	Roles DatabaseRoles `json:"roles,omitempty"`
}

type DatabaseRoles struct {
	// List of users with admin privileges.
	Admin []string `json:"admin,omitempty"`
	// List of users with read-only privileges.
	Readonly []string `json:"readonly,omitempty"`
}

type EndpointCA struct {
	// Key within the Secret containing the CA bundle. Defaults to `ca.crt`.
	// +kubebuilder:default:=""
	Key string `json:"key,omitempty"`
	// Name of the Secret in the application namespace. Empty means no endpointCA is emitted (Barman uses the system trust store).
	// +kubebuilder:default:=""
	Name string `json:"name,omitempty"`
}

type PostgreSQL struct {
	// PostgreSQL server parameters. All values must be strings (quote numbers: "100"). BLOCKED (enable arbitrary code execution): archive_command, restore_command, ssl_passphrase_command, dynamic_library_path, local_preload_libraries, session_preload_libraries, shared_preload_libraries. Do NOT override CloudNativePG-managed parameters: archive_mode, primary_conninfo, wal_level, max_replication_slots.
	// +kubebuilder:default:={"max_connections":"100"}
	Parameters map[string]string `json:"parameters,omitempty"`
}

type Quorum struct {
	// Maximum number of synchronous replicas allowed (must be less than total replicas).
	// +kubebuilder:default:=0
	MaxSyncReplicas int `json:"maxSyncReplicas"`
	// Minimum number of synchronous replicas required for commit.
	// +kubebuilder:default:=0
	MinSyncReplicas int `json:"minSyncReplicas"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type S3CredentialsSecret struct {
	// Key in the Secret holding the access key ID. Defaults to `AWS_ACCESS_KEY_ID`.
	// +kubebuilder:default:=""
	AccessKeyIDKey string `json:"accessKeyIDKey,omitempty"`
	// Name of the Secret in the application namespace. Empty means the chart materialises `<release>-s3-creds` from `s3AccessKey`/`s3SecretKey`.
	// +kubebuilder:default:=""
	Name string `json:"name,omitempty"`
	// Key in the Secret holding the secret access key. Defaults to `AWS_SECRET_ACCESS_KEY`.
	// +kubebuilder:default:=""
	SecretAccessKeyKey string `json:"secretAccessKeyKey,omitempty"`
}

type TLS struct {
	// Tri-state TLS switch. When omitted (null), TLS is enabled automatically if `external` is true and disabled otherwise. Set explicitly to `true` to force TLS on or `false` to force it off regardless of `external`.
	Enabled *bool `json:"enabled,omitempty"`
}

type User struct {
	// Password for the user.
	Password string `json:"password,omitempty"`
	// Whether the user has replication privileges.
	Replication bool `json:"replication,omitempty"`
}

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v18";"v17";"v16";"v15";"v14";"v13"
type Version string
