backupController:
  image: "ghcr.io/cozystack/cozystack/backup-controller:v1.1.7@sha256:92218b53a110b4a4fac5987cc47d1efcb658fb8be20e9ec34dc7d4e359dd0508"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
