kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.1.7@sha256:41d71105d4bd0baf1bd0ea9fdd8ccd0d279717beb8eafc745d0f3f24c15338fe
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.1.7@sha256:41d71105d4bd0baf1bd0ea9fdd8ccd0d279717beb8eafc745d0f3f24c15338fe
