backupStrategyController:
  image: "ghcr.io/cozystack/cozystack/backupstrategy-controller:v1.1.7@sha256:59c3ece89275774c68165cefb095c5f2adbadf154a8fc56ac3971484ba0dc946"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
